export const primaryColor = "#D9251D"
export const secondryColor = "#47CFFF"
export const backgroundColor = "#0F1B2B"
export const primaryTextColor = "#FFFFFF"
export const secondryTextColor = "#313D4D"